# defaults:  
#   - _self_  

# hydra:  
#   output_subdir: null  
#   run:  
#     dir: .

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    
carla:
  host: 'localhost'
  port: 2000
  timeout: 30
  sync:
    fps: 10
    timeout: 30
  seed: 30
  townmap: "Town10HD_Opt"
  traffic_manager_port: 8000
  retry: 10
  # texture: D:\NewPatchGen\Assets\New.png # OG
  texture: D:\NewPatchGen\outputs\2024-01-14\13-53-32\Patch\texture.png
  # texture: D:\NewPatchGen\Assets\Random_noise_100.jpeg # Random Noise
output_dir: "_out2"
max_frames: 10

weather:
  cloudiness: 30.0
  precipitation: 60.0
  precipitation_deposits: 20.0
  wind_intensity: 0.0
  sun_azimuth_angle: 0.0
  sun_altitude_angle: 30.0
  fog_density: 30.0
  fog_distance: 0.0
  wetness: 60.0

spawn_actors:
  # - blueprint:
  #     name: "walker.pedestrian.*"
  #     attr: {role_name: "hero1", is_invincible: "false"}
  #     speed: 1.4  # Between 1 and 2 m/s (default is 1.4 m/s).
  #   transform:
  #     location: {x: 39.40, y: 148.00, z: 0.6}
  #     rotation: {yaw: -90.0}
  #   destination_transform:
  #     location: {x: 39.40, y: 146.00, z: 0.6}

  - blueprint:
      name: "sensor.camera.rgb"
      attr: {"image_size_x": "1280", "image_size_y": "640"}
      speed: 1
    transform:
      location: {x: 25.00, y: 141.60, z: 2.6}
      rotation: {yaw: 0.0}
    destination_transform:
      location: {x: 35.00, y: 141.60, z: 2.6}
    sensor_motion:
      jitter_magnitude: {"x": 0.01, "y": 0.001, "z": 0.01}



