defaults:  
  - _self_  

hydra:  
  output_subdir: null  
  run:  
    dir: .

carla:
  host: 'localhost'
  port: 2000
  timeout: 30
  sync:
    fps: 10
    timeout: 30
  seed: 30
  townmap: "Town10HD_Opt"
  traffic_manager_port: 8000
  retry: 10
  texture: '/home/d99zhang/PycharmProjects/carlaAttack/New.png'

output_dir: "_out"
max_frames: 10

weather:
  cloudiness: 30.0
  precipitation: 60.0
  precipitation_deposits: 50.0
  wind_intensity: 0.0
  sun_azimuth_angle: 0.0
  sun_altitude_angle: 10.0
  fog_density: 20.0
  fog_distance: 0.0
  wetness: 0.0

spawn_actors:
  - blueprint:
      name: "walker.pedestrian.*"
      attr: {role_name: "hero1", is_invincible: "false"}
      speed: 1.4  # Between 1 and 2 m/s (default is 1.4 m/s).
    transform:
      location: {x: 39.40, y: 148.00, z: 0.6}
      rotation: {yaw: -90.0}
    destination_transform:
      location: {x: 39.40, y: 146.00, z: 0.6}

  - blueprint:
      name: "sensor.camera.rgb"
      attr: {"image_size_x": "800", "image_size_y": "600"}
      speed: 1
    transform:
      location: {x: 31.00, y: 141.60, z: 1.6}
      rotation: {yaw: 0.0}
    destination_transform:
      location: {x: 41.00, y: 141.60, z: 1.6}
    sensor_motion:
      jitter_magnitude: {"x": 0.01, "y": 0.001, "z": 0.01}



